### PR TITLE
Sync Release tools repo subtree

### LINKED ISSUE #74: prow image build jobs are failing
**What happened**:

https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/post-external-snapshot-metadata-push-images
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-external-snapshot-metadata-push-images/1857444672650088448
Errors

```
if ! [ "main" ]; then \
	echo >&2 "ERROR: PULL_BASE_REF must be set to 'master', 'release-x.y', or a tag name."; \
	exit 1; \
fi
```

```
+ : 'ERROR: release image gcr.io/k8s-staging-sig-storage/csi-snapshot-metadata:main already exists: a new tag is required!'
+ exit 1
+ docker buildx rm multiarchimage-buildertest
multiarchimage-buildertest removed
make: *** [release-tools/build.make:149: push-multiarch-csi-snapshot-metadata] Error 1
ERROR
ERROR: build step 0 "gcr.io/k8s-testimages/gcb-docker-gcloud:v20230623-56e06d7c18" failed: step exited with non-zero status: 2
```

**What you expected to happen**:

images should be built and pushed successfully.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Rakshith-R**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
This pr syncs release-tools folder with csi-release-tools repository.

**Which issue(s) this PR fixes**:
Resolves #74 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Rakshith-R** [comment]
> /approve

I guess this pr needs /lgtm too

**Review by PrasadG193 — APPROVED** [review]
/lgtm
/approve

**Comment by Rakshith-R** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-csi_external-snapshot-metadata/83/pull-kubernetes-csi-external-snapshot-metadata-unit/1866079543341617152 

maybe a flaky test ?

**Comment by Rakshith-R** [comment]
https://github.com/kubernetes-csi/csi-release-tools/pull/262#issuecomment-2531486038

k8s 1.29 test failure is occuring in all sidecar repos

**Review by PrasadG193 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
